#!/usr/bin/env bash
#Install and Configure HAproxy on lb-01 to send traffic to web-01 and web-02

sudo apt-get update
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y update
sudo apt-get install -y haproxy

cat <<EOL | sudo tee /etc/haproxy/haproxy.cfg
frontend myfrontend
  bind *:80
  mode http
  default_backend myservers
  timeout client 5000s

backend myservers
  balance roundrobin
  mode http
  timeout client 5000s
  timeout server 5000s
  server 400500-web-01 54.144.154.247:80 check
  server 400500-web-02 54.89.27.191:80 check
EOL
sudo service haproxy restart
