#!/usr/bin/env bash
# Displays a list of currently running processes in a user-oriented
# format showing  all processes, in hierarchy for all users,
# including those which might not have a TTY.


ps -auxf
