#!/usr/bin/env bash
# Displays the username, user id and home directory path for the user
# from the /etc/passwd file.

while IFS= read -r username uid home_dir _; do
  echo "$username $uid $home_dir"
done < "/etc/passwd"
