#!/usr/bin/env bash
# Install the ufw firewall and setup a few rules on web-01
# Configure ufw to block all incoming traffic except TCP ports:
# 22, 443, 80

sudo apt install ufw
sudo sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
sudo ufw enable
