#!/usr/bin/env bash
# Configures nginx to run as nginx user with all IPs listening on 8080
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo service nginx restart
