#!/usr/bin/env bash
# Configures nginx to run as nginx user with all IPs listening on 8080

cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
